const CHUNK_PUBLIC_PATH = "server/app/document/[lang]/page.js";
const runtime = require("../../../chunks/ssr/[turbopack]_runtime.js");
runtime.loadChunk("server/chunks/ssr/node_modules_next_dist_c336f25b._.js");
runtime.loadChunk("server/chunks/ssr/[root-of-the-server]__4c58c055._.js");
runtime.loadChunk("server/chunks/ssr/src_app_a4430781._.js");
runtime.loadChunk("server/chunks/ssr/_a2b106f3._.js");
runtime.loadChunk("server/chunks/ssr/node_modules_96715ba7._.js");
runtime.loadChunk("server/chunks/ssr/node_modules_next_dist_client_components_forbidden-error_ea7ea172.js");
runtime.loadChunk("server/chunks/ssr/node_modules_next_dist_client_components_unauthorized-error_c8949b27.js");
runtime.loadChunk("server/chunks/ssr/[root-of-the-server]__e836607c._.js");
runtime.loadChunk("server/chunks/ssr/node_modules_next_fc5ea39e._.js");
runtime.loadChunk("server/chunks/ssr/node_modules_micromark-core-commonmark_dev_lib_35046215._.js");
runtime.loadChunk("server/chunks/ssr/node_modules_mathjax-full_js_core_c332d75d._.js");
runtime.loadChunk("server/chunks/ssr/node_modules_mathjax-full_js_output_common_5167c5a6._.js");
runtime.loadChunk("server/chunks/ssr/node_modules_mathjax-full_js_output_svg_Wrappers_6ecf4d89._.js");
runtime.loadChunk("server/chunks/ssr/node_modules_mathjax-full_js_output_svg_fonts_79a5261a._.js");
runtime.loadChunk("server/chunks/ssr/node_modules_mathjax-full_js_output_svg_d4b74734._.js");
runtime.loadChunk("server/chunks/ssr/node_modules_mathjax-full_js_output_svg_9c764149.js");
runtime.loadChunk("server/chunks/ssr/node_modules_mathjax-full_js_input_3807b1a3._.js");
runtime.loadChunk("server/chunks/ssr/node_modules_mathjax-full_js_180579a3._.js");
runtime.loadChunk("server/chunks/ssr/node_modules_highlight_js_lib_languages_mathematica_673fbb73.js");
runtime.loadChunk("server/chunks/ssr/node_modules_highlight_js_lib_languages_1a5123a1._.js");
runtime.loadChunk("server/chunks/ssr/node_modules_highlight_js_lib_ca5846c8._.js");
runtime.loadChunk("server/chunks/ssr/node_modules_highlight_js_es_index_ebed008c.js");
runtime.loadChunk("server/chunks/ssr/node_modules_iconv-lite_6a12915e._.js");
runtime.loadChunk("server/chunks/ssr/node_modules_@hpcc-js_wasm-graphviz_dist_index_d372381b.js");
runtime.loadChunk("server/chunks/ssr/node_modules_5907c761._.js");
runtime.getOrInstantiateRuntimeModule("[project]/.next-internal/server/app/document/[lang]/page/actions.js [app-rsc] (server actions loader, ecmascript)", CHUNK_PUBLIC_PATH);
runtime.getOrInstantiateRuntimeModule("[project]/node_modules/next/dist/esm/build/templates/app-page.js?page=/document/[lang]/page { METADATA_0 => \"[project]/src/app/favicon.ico.mjs { IMAGE => \\\"[project]/src/app/favicon.ico (static in ecmascript)\\\" } [app-rsc] (structured image object, ecmascript, Next.js server component)\", MODULE_1 => \"[project]/src/app/layout.tsx [app-rsc] (ecmascript, Next.js server component)\", MODULE_2 => \"[project]/node_modules/next/dist/client/components/not-found-error.js [app-rsc] (ecmascript, Next.js server component)\", MODULE_3 => \"[project]/node_modules/next/dist/client/components/forbidden-error.js [app-rsc] (ecmascript, Next.js server component)\", MODULE_4 => \"[project]/node_modules/next/dist/client/components/unauthorized-error.js [app-rsc] (ecmascript, Next.js server component)\", MODULE_5 => \"[project]/src/app/document/[lang]/page.tsx [app-rsc] (ecmascript, Next.js server component)\" } [app-rsc] (ecmascript)", CHUNK_PUBLIC_PATH);
module.exports = runtime.getOrInstantiateRuntimeModule("[project]/node_modules/next/dist/esm/build/templates/app-page.js?page=/document/[lang]/page { METADATA_0 => \"[project]/src/app/favicon.ico.mjs { IMAGE => \\\"[project]/src/app/favicon.ico (static in ecmascript)\\\" } [app-rsc] (structured image object, ecmascript, Next.js server component)\", MODULE_1 => \"[project]/src/app/layout.tsx [app-rsc] (ecmascript, Next.js server component)\", MODULE_2 => \"[project]/node_modules/next/dist/client/components/not-found-error.js [app-rsc] (ecmascript, Next.js server component)\", MODULE_3 => \"[project]/node_modules/next/dist/client/components/forbidden-error.js [app-rsc] (ecmascript, Next.js server component)\", MODULE_4 => \"[project]/node_modules/next/dist/client/components/unauthorized-error.js [app-rsc] (ecmascript, Next.js server component)\", MODULE_5 => \"[project]/src/app/document/[lang]/page.tsx [app-rsc] (ecmascript, Next.js server component)\" } [app-rsc] (ecmascript)", CHUNK_PUBLIC_PATH).exports;
